import { QuestionPaper } from '../types/paper';
import { QuestionAnalysis } from '../types/question';
import { OverviewAnalytics, BloomAnalyticsData, TrendsAnalyticsData } from '../types/analytics';

export const MOCK_PAPERS: QuestionPaper[] = [
  {
    id: 101,
    subject_id: 1,
    subject_code: 'CS301',
    subject_name: 'Database Management Systems',
    examination_type: 'End-Semester',
    maximum_marks: 100,
    original_filename: 'CS301_EndSem_2024.pdf',
    upload_timestamp: '2024-05-15T10:30:00Z',
    year_date: 'May 2024',
    processing_status: 'COMPLETED',
    extraction_status: 'SUCCESS',
    validation_status: 'VALID',
    optional_question_flag: false,
    total_questions: 10,
    validation_metadata: {
      status: 'valid',
      maximum_marks: 100,
      extracted_marks: 100,
      missing_marks_count: 0,
      possible_reasons: [],
    },
  },
  {
    id: 102,
    subject_id: 2,
    subject_code: 'CS201',
    subject_name: 'Data Structures & Algorithms',
    examination_type: 'Mid-Term',
    maximum_marks: 50,
    original_filename: 'DSA_MidTerm_Nov2023.docx',
    upload_timestamp: '2023-11-20T14:15:00Z',
    year_date: 'Nov 2023',
    processing_status: 'COMPLETED',
    extraction_status: 'SUCCESS',
    validation_status: 'UNCERTAIN',
    optional_question_flag: true,
    total_questions: 8,
    validation_metadata: {
      status: 'uncertain',
      maximum_marks: 50,
      extracted_marks: 45,
      missing_marks_count: 1,
      possible_reasons: ['optional_question_structure', 'marks_extraction_error'],
    },
  },
  {
    id: 103,
    subject_id: 3,
    subject_code: 'CS304',
    subject_name: 'Operating Systems',
    examination_type: 'Internal Test',
    maximum_marks: 30,
    original_filename: 'OS_Internal2_2024.pdf',
    upload_timestamp: '2024-03-10T09:00:00Z',
    year_date: 'Mar 2024',
    processing_status: 'COMPLETED',
    extraction_status: 'SUCCESS',
    validation_status: 'VALID',
    optional_question_flag: false,
    total_questions: 6,
  },
];

export const MOCK_QUESTIONS_MAP: Record<number, QuestionAnalysis[]> = {
  101: [
    {
      id: 1001,
      question_paper_id: 101,
      question_number: 'Q1',
      original_text: 'Define database normalization and state its primary objectives in relational database design.',
      marks: 5,
      marks_confidence: 'high',
      ai_bloom_level: 'Remember',
      effective_bloom_level: 'Remember',
      bloom_confidence: 0.94,
      bloom_explanation: 'Question uses verb "Define" and asks for direct recall of foundational DBMS concepts.',
      ai_question_type: 'Definition',
      question_type: 'Definition',
      unit: 'Unit 2',
      topic: 'Normalization & Normal Forms',
      review_status: 'AUTO_CLASSIFIED',
      ai_analysis_metadata: {
        classifier_source: 'hybrid',
        detected_verbs: ['define', 'state'],
        cognitive_operation: 'Recall of fundamental database concepts',
        component_scores: { verb_score: 0.95, semantic_score: 0.90, cognitive_score: 0.92, structure_score: 0.85 },
      },
    },
    {
      id: 1002,
      question_paper_id: 101,
      question_number: 'Q2',
      original_text: 'Explain the ACID properties of database transactions and discuss how isolation levels affect concurrency.',
      marks: 10,
      marks_confidence: 'high',
      ai_bloom_level: 'Understand',
      effective_bloom_level: 'Understand',
      bloom_confidence: 0.89,
      bloom_explanation: 'Target cognitive task requires explaining underlying mechanisms of transactional isolation.',
      ai_question_type: 'Descriptive',
      question_type: 'Descriptive',
      unit: 'Unit 3',
      topic: 'Transaction Management',
      review_status: 'AUTO_CLASSIFIED',
      ai_analysis_metadata: {
        classifier_source: 'hybrid',
        detected_verbs: ['explain', 'discuss'],
        cognitive_operation: 'Understanding transactional semantics',
        component_scores: { verb_score: 0.88, semantic_score: 0.89, cognitive_score: 0.85, structure_score: 0.80 },
      },
    },
    {
      id: 1003,
      question_paper_id: 101,
      question_number: 'Q3',
      original_text: 'Given relation R(A, B, C, D) with functional dependencies F = {A -> B, BC -> D}, apply 3NF normalization to decompose R into 3NF relations.',
      marks: 12,
      marks_confidence: 'high',
      ai_bloom_level: 'Apply',
      effective_bloom_level: 'Apply',
      bloom_confidence: 0.91,
      bloom_explanation: 'Question requires executing the 3NF decomposition algorithm on a specific set of functional dependencies.',
      ai_question_type: 'Problem Solving',
      question_type: 'Problem Solving',
      unit: 'Unit 2',
      topic: 'Normalization & Normal Forms',
      review_status: 'AUTO_CLASSIFIED',
      ai_analysis_metadata: {
        classifier_source: 'hybrid',
        detected_verbs: ['apply', 'decompose'],
        cognitive_operation: 'Procedural application of normalization rules',
        component_scores: { verb_score: 0.90, semantic_score: 0.92, cognitive_score: 0.91, structure_score: 0.88 },
      },
    },
    {
      id: 1004,
      question_paper_id: 101,
      question_number: 'Q4(a)',
      parent_question_id: 10040,
      original_text: 'Compare 2NF and 3NF normalization forms. Highlight key differences regarding transitive dependencies.',
      marks: 8,
      marks_confidence: 'high',
      ai_bloom_level: 'Analyze',
      effective_bloom_level: 'Analyze',
      bloom_confidence: 0.92,
      bloom_explanation: 'Requires differentiating and contrasting structural constraints between 2NF and 3NF.',
      ai_question_type: 'Comparison',
      question_type: 'Comparison',
      unit: 'Unit 2',
      topic: 'Normalization & Normal Forms',
      review_status: 'AUTO_CLASSIFIED',
      ai_analysis_metadata: {
        classifier_source: 'hybrid',
        detected_verbs: ['compare', 'differentiate'],
        cognitive_operation: 'Comparative structural analysis',
        component_scores: { verb_score: 0.94, semantic_score: 0.91, cognitive_score: 0.90, structure_score: 0.86 },
      },
    },
    {
      id: 1005,
      question_paper_id: 101,
      question_number: 'Q4(b)',
      parent_question_id: 10040,
      original_text: 'Evaluate whether BCNF is always preferable to 3NF for high-throughput OLTP systems. Justify your argument with trade-offs.',
      marks: 10,
      marks_confidence: 'high',
      ai_bloom_level: 'Evaluate',
      effective_bloom_level: 'Evaluate',
      bloom_confidence: 0.86,
      bloom_explanation: 'Requires making a critical judgment and defending a choice based on performance metrics vs dependency preservation.',
      ai_question_type: 'Descriptive',
      question_type: 'Descriptive',
      unit: 'Unit 2',
      topic: 'Normalization & Normal Forms',
      review_status: 'AUTO_CLASSIFIED',
      ai_analysis_metadata: {
        classifier_source: 'gemini_verified',
        detected_verbs: ['evaluate', 'justify'],
        cognitive_operation: 'Critical assessment and trade-off evaluation',
        component_scores: { verb_score: 0.85, semantic_score: 0.84, cognitive_score: 0.87, structure_score: 0.85 },
      },
    },
    {
      id: 1006,
      question_paper_id: 101,
      question_number: 'Q5',
      original_text: 'Design a complete normalized relational database schema for a multi-vendor e-commerce platform supporting cart, orders, and payment tracking.',
      marks: 15,
      marks_confidence: 'high',
      ai_bloom_level: 'Create',
      effective_bloom_level: 'Create',
      bloom_confidence: 0.95,
      bloom_explanation: 'Requires synthesizing a novel, multi-entity relational schema architecture from scratch.',
      ai_question_type: 'Design',
      question_type: 'Design',
      unit: 'Unit 1',
      topic: 'Relational Schema Design',
      review_status: 'AUTO_CLASSIFIED',
      ai_analysis_metadata: {
        classifier_source: 'hybrid',
        detected_verbs: ['design', 'construct'],
        cognitive_operation: 'Synthesis of a novel database schema architecture',
        component_scores: { verb_score: 0.96, semantic_score: 0.95, cognitive_score: 0.94, structure_score: 0.92 },
      },
    },
    {
      id: 1007,
      question_paper_id: 101,
      question_number: 'Q6',
      original_text: 'Write an SQL query to find top 5 customers with highest purchase total.',
      marks: null, // Test missing marks
      marks_confidence: 'low',
      ai_bloom_level: 'Apply',
      effective_bloom_level: 'Apply',
      bloom_confidence: 0.58, // Low confidence test!
      bloom_explanation: 'Low confidence signal. Query writing may involve application or routine syntax construction.',
      ai_question_type: 'Programming',
      question_type: 'Programming',
      unit: 'Unit 4',
      topic: 'SQL & Relational Algebra',
      review_status: 'FLAGGED',
      ai_analysis_metadata: {
        classifier_source: 'hybrid',
        detected_verbs: ['write'],
        cognitive_operation: 'Uncertain cognitive operation',
        component_scores: { verb_score: 0.55, semantic_score: 0.60, cognitive_score: 0.58, structure_score: 0.50 },
      },
    },
    {
      id: 1008,
      question_paper_id: 101,
      question_number: 'Q7',
      original_text: 'Fragmented text: ... indexing B+ Tree leaf nodes ... [Unparsed section]',
      marks: 5,
      marks_confidence: 'low',
      ai_bloom_level: null, // Missing Bloom classification test!
      effective_bloom_level: null,
      bloom_confidence: null,
      bloom_explanation: 'Extraction incomplete due to document OCR ambiguity.',
      ai_question_type: null,
      question_type: null,
      unit: 'Unit 4',
      topic: 'Indexing & Hashing',
      review_status: 'FLAGGED',
      extraction_confidence: 0.40,
    },
  ],
};

export const MOCK_OVERVIEW_ANALYTICS: OverviewAnalytics = {
  papers_analyzed: 12,
  questions_analyzed: 148,
  subjects_count: 4,
  topics_count: 28,
  total_relevant_marks: 1250,
};

export const MOCK_BLOOM_ANALYTICS: BloomAnalyticsData = {
  total_questions: 10,
  total_marks: 100,
  distributions: [
    { bloom_level: 'L1', name: 'Remember', question_count: 2, question_count_percentage: 20, total_marks: 15, marks_percentage: 15 },
    { bloom_level: 'L2', name: 'Understand', question_count: 2, question_count_percentage: 20, total_marks: 20, marks_percentage: 20 },
    { bloom_level: 'L3', name: 'Apply', question_count: 2, question_count_percentage: 20, total_marks: 22, marks_percentage: 22 },
    { bloom_level: 'L4', name: 'Analyze', question_count: 2, question_count_percentage: 20, total_marks: 18, marks_percentage: 18 },
    { bloom_level: 'L5', name: 'Evaluate', question_count: 1, question_count_percentage: 10, total_marks: 10, marks_percentage: 10 },
    { bloom_level: 'L6', name: 'Create', question_count: 1, question_count_percentage: 10, total_marks: 15, marks_percentage: 15 },
  ],
};

export const MOCK_TRENDS_ANALYTICS: TrendsAnalyticsData = {
  metric_type: 'marks_weighted',
  trends: [
    { paper: '2021 End-Sem', year: '2021', L1: 30, L2: 25, L3: 20, L4: 15, L5: 10, L6: 0 },
    { paper: '2022 End-Sem', year: '2022', L1: 25, L2: 25, L3: 25, L4: 15, L5: 5, L6: 5 },
    { paper: '2023 End-Sem', year: '2023', L1: 20, L2: 20, L3: 25, L4: 20, L5: 10, L6: 5 },
    { paper: '2024 End-Sem', year: '2024', L1: 15, L2: 20, L3: 22, L4: 18, L5: 10, L6: 15 },
  ],
};
