"""Add co_mapping and choice_group columns

Revision ID: 04d536a736a7
Revises: 001_initial
Create Date: 2026-08-16 10:27:30.777698+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d536a736a7'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('co_mapping', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('choice_group', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_questions_choice_group'), 'questions', ['choice_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_choice_group'), table_name='questions')
    op.drop_column('questions', 'choice_group')
    op.drop_column('questions', 'co_mapping')
    # ### end Alembic commands ###
