"""Pydantic schemas for request validation and API responses."""

from app.schemas.course import (
    CourseBase,
    CourseCreate,
    CourseUpdate,
    CourseOutcomeBase,
    CourseOutcomeCreate,
    CourseOutcomeUpdate,
    CourseOutcomeResponse,
    CourseResponse,
    CourseWithOutcomesResponse,
    CourseListResponse,
    CourseOutcomeListResponse,
    CourseBulkOutcomeItem,
    CourseBulkOutcomeRequest,
    COExtractTextRequest,
    COExtractedItem,
    COExtractionPreviewResponse,
    COImportConfirmItem,
    COImportConfirmRequest,
    COImportConfirmResponse,
)
from app.schemas.co_mapping import (
    COScoreBreakdown,
    COMappingCandidate,
    QuestionCOMappingResult,
    QuestionCOMappingRequest,
    BatchCOPaperMappingRequest,
    BatchCOMappingResponse,
    QuestionCOMappingRecordResponse,
    GeminiCOMappingResponse,
)

__all__ = [
    "CourseBase",
    "CourseCreate",
    "CourseUpdate",
    "CourseOutcomeBase",
    "CourseOutcomeCreate",
    "CourseOutcomeUpdate",
    "CourseOutcomeResponse",
    "CourseResponse",
    "CourseWithOutcomesResponse",
    "CourseListResponse",
    "CourseOutcomeListResponse",
    "CourseBulkOutcomeItem",
    "CourseBulkOutcomeRequest",
    "COExtractTextRequest",
    "COExtractedItem",
    "COExtractionPreviewResponse",
    "COImportConfirmItem",
    "COImportConfirmRequest",
    "COImportConfirmResponse",
    "COScoreBreakdown",
    "COMappingCandidate",
    "QuestionCOMappingResult",
    "QuestionCOMappingRequest",
    "BatchCOPaperMappingRequest",
    "BatchCOMappingResponse",
    "QuestionCOMappingRecordResponse",
    "GeminiCOMappingResponse",
]
